ecommerceproject/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add/<int:product_id>/', views.add_cart, name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('full_remove/<int:product_id>/', views.full_remove, name='full_remove'),
]

ecommerceproject/ecommerceapp/urls.py
from . import views
from django.urls import path

app_name = 'ecommerceapp'
urlpatterns = [
    path('', views.allProdCat, name='allProdCat'),
    path('<slug:c_slug>/', views.allProdCat, name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.product_details, name='product_details'),
]

ecommerceproject/ecommerceproject/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('ecommerceapp.urls')),
    path('search/', include('searchapp.urls')),
    path('cart/', include('cart.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ecommerceproject/searchapp/urls.py
from django.urls import path
from . import views

app_name = 'searchapp'

urlpatterns = [
   path('', views.search_result, name='search_result'),
]

ecommerceproject/cart/models.py
from django.db import models
from ecommerceapp.models import Product
# Create your models here.
class Cart(models.Model):
    cart_id = models.CharField(max_length=200, blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)

class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

ecommerceproject/ecommerceapp/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='category', blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse('ecommerceapp:products_by_category', args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)

class Product(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='product', blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    stock = models.IntegerField()
    availability = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def get_url(self):
        return reverse('ecommerceapp:product_details', args=[self.category.slug, self.slug])

    def __str__(self):
        return '{}'.format(self.name)

ecommerceproject/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from ecommerceapp.models import Product
from . models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.
def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart

def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id=_cart_id(request))
    cart.save()
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(product=product, quantity=1, cart=cart)
        cart_item.save()
    return redirect('cart:cart_detail')

def cart_detail(request, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id = _cart_id(request))
        cart_items = CartItem.objects.filter(cart= cart, active= True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request, 'cart.html', dict(cart_items=cart_items, total=total, counter=counter))

def cart_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')

def full_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()

    return redirect('cart:cart_detail')

ecommerceproject/ecommerceapp/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from django.core.paginator import Paginator, EmptyPage, InvalidPage


# Create your views here.
def allProdCat(request, c_slug=None):
    c_page = None
    products_list = None
    if c_slug is not None:
        c_page = get_object_or_404(Category, slug=c_slug)
        products_list = Product.objects.all().filter(category=c_page, availability=True)

    else:
        products_list = Product.objects.all().filter(availability=True)

    paginator = Paginator(products_list, 6)

    try:
        page = int(request.GET.get('page', '1'))
    except:
        page = 1

    try:
        products = paginator.page(page)
    except (EmptyPage, InvalidPage):
        products = paginator.page(paginator.num_pages)

    return render(request, "category.html", {'category': c_page, 'products': products})


def product_details(request, c_slug, product_slug):
    try:
        product = Product.objects.get(category__slug=c_slug, slug=product_slug)
    except Exception as e:
        raise e
    return render(request, 'product.html', {'product': product})

ecommerceproject/searchapp/views.py
from django.shortcuts import render
from ecommerceapp.models import Product
from django.db.models import Q
# Create your views here.

def search_result(request):
    products: None
    query: None
    if 'q' in request.GET:
        query = request.GET.get('q')
        products = Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
        return render(request, 'search.html', {'query': query, 'products': products})

ecommerceproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{% block metadescription %}{% endblock %}">

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans&display=swap" rel="stylesheet">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/0687cbebce.js" crossorigin="anonymous"></script>

    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="container">
    {% include 'header.html' %}
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}
</div>
<br>
{% include 'footer.html' %}
<script src="{% static 'js/jquery.slim.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

ecommerceproject/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    This is the cart page. Proceed to review your items and place the order
{% endblock %}
{% block title %}
    Cart - Thrive pvt ltd
{% endblock %}
{% block content %}
{% if not cart_items %}
<div class="container">
    <div class="text-center">
        <br>
        <h3 class="text-center my_title">Your cart is empty</h3>
        <br>
        <p class="text-center">
            please click here to add items to cart <br>
            <a href="{% url 'ecommerceapp:allProdCat' %}" class="btn btn-secondary">Add item</a>
        </p>
    </div>
</div>
{% else %}
<div class="container">
    <div class="text-center">
        <br>
        <h2 class="text-center my_title">Your cart</h2>
        <br>
    </div>
</div>
<div class="container">
    <div class="row mx_auto">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <table class="table my_custom_table">
                <thead class="my_custom_head">
                    <tr>
                        <th colspan="5">Your items</th>
                    </tr>
                </thead>
                <tbody>
                {% for cart_item in cart_items %}
                <tr>
                    <td>
                        <a href="art_item.product.get_absolute_url">
                            <img src="{{cart_item.product.image.url}}" alt="product_image" class="float-left rounded custom_image" style="width: ; height: 200px;">
                        </a>
                    </td>
                    <td class="text-left">
                        {{cart_item.product.name}}
                        <br>
                        SKU: {{cart_item.product.id}}
                        <br>
                        Price: $ {{cart_item.product.price}}
                        <br>
                        Qty: {{cart_item.quantity}} <!--x $ {{cart_item}}-->
                    </td>
                    <td>
                        ${{cart_item.sub_total}}
                    </td>
                    {% if cart_item.quantity < cart_item.product.stock %}
                    <td>
                        &nbsp;<a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a">
                            <i class="fa-solid fa-circle-plus custom_icon"></i>
                        </a><br>
                        &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a">
                            <i class="fa-solid fa-circle-minus custom_icon"></i>
                        </a><br>
                        &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon">
                            <i class="fa-solid fa-trash custom_icon"></i>
                        </a>
                    </td>
                    {% else %}
                    <td>
                        &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a">
                            <i class="fa-solid fa-circle-minus custom_icon"></i>
                        </a><br>
                        &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon">
                            <i class="fa-solid fa-trash custom_icon"></i>
                        </a><br>
                    </td>
                    {% endif %}
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <table class="table my_custom_table">
                <thead class="my_custom_head">
                    <tr>
                        <th>
                            checkout
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            Please review your cart items before proceeding with payment.
                        </td>
                    </tr>
                    <tr>
                        <td class="text-left">
                            Your total amount is : <strong>{{ total }}</strong>
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="mx_auto">
               <a href="{% url 'ecommerceapp:allProdCat' %}" class="btn btn-secondary btn-block my_custom_button">Go back to shopping</a>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

ecommerceproject/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{ category.description|truncatewords:150 }}
    {% else %}
        Welcome to Thrive haberdashery. Your first and best choice!
    {% endif %}
{% endblock %}

{% block title %}
    {% if category %}
        {{ category.name }} -Collections -Thrive
    {% else %}
        Thrive
    {% endif %}
{% endblock %}

{% block content %}
    {% if category %}
        <div>
            <div class="row my_row_class">
                <div class="mx-auto">
                    <p class="my_tile"><a href="{% url 'ecommerceapp:allProdCat' %}">Our Collections</a>| {{category.name}}</p>
                </div>
            </div>
        </div>
    {% endif %}
    <div class="mx-auto">
        {% if category %}
            <img class="my_image" src="{{ category.image.url }}" alt="{{ category.name }}">
    </div>
        <br>
    <div>
        <h1 class="text-center my_title">{{ category.name }}</h1>
        <p class="text-justify">{{ category.description }}</p>
    </div>
        {% else %}
        <div id="carouselExample" class="carousel slide">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="{% static 'images/banner_1.png' %}" class="d-block w-100" alt="banner">
                </div>
                <div class="carousel-item">
                    <img src="{% static 'images/banner_2.png' %}" class="d-block w-100" alt="banner">
                </div>
                <div class="carousel-item">
                    <img src="{% static 'images/banner_3.png' %}" class="d-block w-100" alt="banner">
                </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>
        <br>
        <div>
            <h1 class="text-center my_title"> Our collections </h1>
            <p class="text-justify">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed molestie scelerisque diam, id dictum sapien scelerisque sed. Nunc lobortis ligula id venenatis ultrices. Morbi finibus metus vel arcu commodo consequat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed dui dolor, lobortis vel est non, hendrerit fringilla eros.</p>
        </div>
        {% endif %}
    <div class="container">
        <div class="row mx_auto">
           {% for product in products.object_list %}
                <div class="col-md-4 my_bottom_margin">
                    <div class="card text-center" style="width: 17rem;">
                        <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}" height="300"></a>
                        <div class="card-body">
                           <h5 class="card-title">{{ product.name }}</h5>
                           <p class="card-text">$ {{ product.price }}</p>
                        </div>
                    </div>
                </div>
           {% endfor %}
        </div>
        <div class="mx_auto">
            {% if products.paginator.num_pages > 1 %}
                <hr>
                <div class="text-center">
                    {% for pg in products.paginator.page_range %}
                        <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

ecommerceproject/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
    <p class="text-center">&copy; Thrive pvt ltd. All rights Reserved</p>
</div>

ecommerceproject/templates/header.html
{% load static %}
<header>
    <div class="container" id="logo-container">
        <a href="{% url 'ecommerceapp:allProdCat' %}"><img src="{% static 'images/pg-logo.png' %}" alt="logo-image" id="logo"></a>
    </div>
</header>

ecommerceproject/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
</head>
<body>
    welcome :)
</body>
</html>

ecommerceproject/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-transparent d-flex justify-content-center mx-auto">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="nav-link active" aria-current="page" href="/shop/"><i class="fa-solid fa-house"></i>Home</a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle active" aria-current="page" href="{% url 'ecommerceapp:allProdCat' %}" role="button" data-bs-toggle="dropdown" aria-expanded="false">All Collections</a>
                    <ul class="dropdown-menu">
                        {% for cat in links %}
                        <li><a class="dropdown-item" aria-current="page" href="{{cat.get_url}}">{{cat.name}}</a></li>
                        {% endfor %}
                    </ul>
                </li>
                {% if item_count >= 0 %}
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'cart:cart_detail' %}">Cart<i class="fa-solid fa-cart-shopping"></i>({{item_count}})</a>
                </li>
                {% endif %}
            </ul>
            <form class="d-flex" role="search" action="{% url 'searchapp:search_result' %}" method="get">
                {% csrf_token %}
                <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
                <button class="btn btn-outline-success" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
            </form>
        </div>
    </div>
</nav>

ecommerceproject/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {{ product.description|truncatewords:150 }}
{% endblock %}

{% block title %}
    {% if category %}
        {{ product.name }} -Collections -Thrive
    {% endif %}
{% endblock %}

{% block content %}
<div class="row my_prod_class">
    <div class="mx_auto">
        <p>
            <a href="{% url 'ecommerceapp:allProdCat' %}">Home</a>| <a href="{{product.category.get_url}}">
            {{product.category}}</a> | {{product.name}}
        </p>
    </div>
    <div class="container">
        <br>
        <div class="row">
            <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                <div style="min-width: 18rem;">
                    <img src="{{product.image.url}}" alt="{{product.name}}" style="height: 400px;">
                </div>
            </div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-6">
                <div>
                    <h2 class="my_prod_title">{{product.name}}</h2>
                    <p>$ {{product.price}}</p>
                    <p class="text-justify my_prod_text">{{product.description}}</p>
                    {% if product.stock <= 0 %}
                        <p class="text-justify my_prod_text"><b>Out of stock</b></p>
                    {% else %}
                        <a class="btn btn-primary" href="{% url 'cart:add_cart' product.id %}">Add to cart</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

ecommerceproject/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    Explore the wide range of top-notch collections!
{% endblock %}
{% block title %}
    Search
{% endblock %}
{% block content %}
<div>
    <p class="text-center my_search_text">
        You have searched for: <b>"{{query}}"</b>
    </p>
</div>
<div class="container">
    <div class="row mx_auto">
        {% for product in products %}
            <div class="col-md-4 my_bottom_margin">
                <div class="card text-center" style="width: 17rem;">
                    <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}" height="300"></a>
                    <div class="card-body">
                        <h5 class="card-title">{{ product.name }}</h5>
                        <p class="card-text">$ {{ product.price }}</p>
                    </div>
                </div>
            </div>
            {% empty %}
            <div class="row mx_auto">
                <p class="text-center ,y_search_text">0 results found.</p>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}