school_project/credentials/urls.py
from . import views
from django.urls import path

app_name = 'credentials'
urlpatterns = [
    path('register', views.register, name='register'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('btn', views.btn, name='btn'),
]

school_project/school_app/urls.py
from . import views
from django.urls import path

app_name = 'school_app'
urlpatterns = [
    path('', views.Alldep, name='Alldep'),
]

school_project/school_project/urls.py
from django.contrib import admin
from django.urls import path, include
from school_project import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('school_app.urls')),
    path('credentials/', include('credentials.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

school_project/credentials/models.py
from django.db import models

# Create your models here.

school_project/school_app/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    name = models.CharField(max_length=200)
    username = models.CharField(max_length=200, unique=True)
    password = models.CharField(max_length=200)
    c_password = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Department(models.Model):
    dep_name = models.CharField(max_length=200, unique=True)
    img = models.ImageField(upload_to='pics')
    desc = models.TextField()
    link = models.URLField(max_length=200)

    def __str__(self):
        return self.dep_name

class Course(models.Model):
    course_name = models.CharField(max_length=255)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    description = models.TextField()

    def __str__(self):
        return self.course_name

school_project/credentials/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
# Create your views here.

def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        c_password = request.POST['c_password']

        if password == c_password:
            if User.objects.filter(username=username).exists():
                # messages.info(request, "username already taken")
                return redirect('register')
            else:
                user = User.objects.create_user(username=username,password=password)
                user.save()
                # messages.info(request, "user added successfully")
                return render(request, "login.html")
        else:
            # messages.info(request, "password not matching")
            return redirect('register')

    return render(request, "register.html")

def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            return render(request, 'home.html')
        else:
            messages.info(request, "invalid credentials")
            return redirect('login')

    return render(request, "login.html")

def logout(request):
    auth.logout(request)
    return redirect('/')

def btn(request):
    return render(request, "form.html")

school_project/school_app/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from .models import Department
# Create your views here.

def Alldep(request):
    dep = Department.objects.all()

    return render(request,'index.html', {'dept':dep})

school_project/templates/form.html
{% load static %}
<!DOCTYPE html>
<html lang="en" data-bs-theme="light">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    <title>Sky High</title>

    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    <script src="https://kit.fontawesome.com/0687cbebce.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

    <style>
        form {
            width: 50%;
            margin: 0 auto;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 5px;
        }
        label {
            display: block;
            margin-bottom: 5px;
        }
        input, select {
            width: 100%;
            padding: 5px;
            margin-bottom: 10px;
            border: 1px solid #ddd;
            border-radius: 3px;
        }
        .checkbox-group {
            margin: 10px 0;
        }
        .checkbox {
            display: inline-block;
            margin-right: 10px;
        }
        input[type="submit"] {
            background-color: #007bff;
            color: #fff;
            /* padding: 10px; */
            border: none;
            width: 50%;
            border-radius: 5px;
            cursor: pointer;
        }
        .logout-btn a{
            float: right;
        }

                    /* The Modal (background) */
            .modal {
                display: none; /* Hidden by default */
                position: fixed; /* Stay in place */
                z-index: 1; /* Sit on top */
                padding-top: 100px; /* Location of the box */
                left: 0;
                top: 0;
                width: 100%; /* Full width */
                height: 100%; /* Full height */
                overflow: auto; /* Enable scroll if needed */
                background-color: rgb(0,0,0); /* Fallback color */
                background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
            }

            /* Modal Content */
            .modal-content {
                background-color: #fefefe;
                margin: auto;
                padding: 20px;
                border: 1px solid #888;
                width: 80%;
            }

            /* The Close Button */
            .close {
                color: #aaaaaa;
                float: right;
                font-size: 28px;
                font-weight: bold;
            }

            .close:hover,
            .close:focus {
                color: #000;
                text-decoration: none;
                cursor: pointer;
            }
    </style>
</head>
<body>
    <div>
        {% include 'header.html' %}
    </div>
    <br><br>
    <div class="container logout-btn">
        <a type="button" class="btn btn-warning" href="{% url 'credentials:logout' %}">Logout</a>
    </div>
    <div>
        <form method="POST" id="course-form" onsubmit="return submitForm();">
            {% csrf_token %}
            <table>
                <h4>Student Information</h4>
                <tr>
                    <td>
                        <label for="name">Name</label>
                    </td>
                    <td>
                        <input type="text" id="name" name="name" required>
                    </td>
                </tr>
                <tr>
                    <td>
                        <label for="dob">Date of Birth</label>
                    </td>
                    <td>
                        <input type="date" id="dob" name="dob" required>
                    </td>
                </tr>
                <tr>
                    <td>
                        <label for="age">Age</label>
                    </td>
                    <td>
                        <input type="number" id="age" name="age" required>
                    </td>
                </tr>
                <tr>
                    <td>
                        <label for="gender">Gender</label>
                    </td>
                    <td>
                        <select id="gender" name="gender">
                            <option value="">Select</option>
                            <option value="male">Male</option>
                            <option value="female">Female</option>
                            <option value="other">Other</option>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td>
                        <label for="phone">Phone number</label>
                    </td>
                    <td>
                        <input type="tel" id="phone" name="phone" pattern="[0-9]{10}" required>
                    </td>
                </tr>
                <tr>
                    <td>
                        <label for="email">Email id</label>
                    </td>
                    <td>
                        <input type="email" id="email" name="email" required>
                    </td>
                </tr>
                <tr>
                    <td>
                        <label for="address">Address</label>
                    </td>
                    <td>
                        <textarea name="address" id="address" rows="5"></textarea>
                    </td>
                </tr>
                <tr>
                    <td>
                        <h4>Department and Courses</h4>
                    </td>
                </tr>
                <tr>
                    <td>
                        <label for="department">Department</label>
                    </td>
                    <td>
                        <select id="department" name="department">
                            <option value="">Select Department</option>
                            <option value="computer_science">Computer Science</option>
                            <option value="physics">Physics</option>
                            <option value="commerce">Commerce</option>
                            <option value="biology">Biology</option>
                            <option value="literature">Literature</option>
                            <option value="mathematics">Mathematics</option>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td>
                        <label for="course">Course</label>
                    </td>
                    <td>
                        <select name="course" id="course">
                            <option value="">Select Course</option>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td>
                        <h4>Purpose and Materials</h4>
                    </td>
                </tr>
                <tr>
                    <td>
                        <label for="purpose">Purpose</label>
                    </td>
                    <td>
                        <select id="purpose" name="purpose">
                            <option value="">Select Purpose</option>
                            <option value="enquiry">Enquiry</option>
                            <option value="order">Place Order</option>
                            <option value="return">Return</option>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td>
                        <label for="materials">Materials Provided</label>
                    </td>
                    <td>
                        <div class="checkbox-group">
                            <label class="checkbox">
                                <input type="checkbox" id="debit_note" name="materials[]" value="Debit Note Book">
                                    Debit Note Book
                            </label>
                            <label class="checkbox">
                                <input type="checkbox" id="pen" name="materials[]" value="Pen">
                                    Pen
                            </label>
                            <label class="checkbox">
                                <input type="checkbox" id="exam_papers" name="materials[]" value="Exam Papers">
                                    Exam Papers
                            </label>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <button type="submit" class="btn btn-primary" onclick="return showAlert();">Submit</button>
                    </td>
                </tr>
            </table>
        </form>  
        <div id="myModal" class="modal">
            <div class="modal-content">
                <span class="close">&times;</span>
                <p>Form submitted. Click <a href="/" target="_blank">here</a> to go home</p>
            </div>
        </div>  
    </div><br><br><br><br>
    <div>
        <footer class="bg-dark text-light py-3">
            <div class="container">
                <div class="row">
                    <div class="col-md-4">
                        <h5>About</h5>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                    </div>
                    <div class="col-md-4">
                        <h5>Contact</h5>
                        <p>Phone: +1 234 567 890</p>
                        <p>Email: example@example.com</p>
                    </div>
                    <div class="col-md-4">
                        <h5>Follow us on</h5>
                        <a href="https://www.facebook.com/" class="btn btn-light btn-sm mx-1">
                            <i class="fa-brands fa-facebook"></i>
                        </a>
                        <a href="https://www.instagram.com/" class="btn btn-light btn-sm mx-1">
                            <i class="fa-brands fa-instagram"></i>
                        </a>
                        <a href="https://twitter.com/i/flow/login" class="btn btn-light btn-sm mx-1">
                            <i class="fa-brands fa-twitter"></i>
                        </a>
                    </div>
                </div>
            </div>
        </footer>
    </div>
</body>

<script>
        // Object to store departments and their corresponding courses
    const coursesByDepartment = {
    computer_science: ["BSc Computer Science", "MSc Computer Science", "MCA", "BCA"],
    physics: ["BSc Physics", "MSc Physics", "PhD Physics"],
    mathematics: ["BSc Mathematics", "MSc Mathematics", "PhD Mathematics"],
    commerce: ["BCom", "MCom", "BBA", "MBA"],
    chemistry: ["BSc Chemistry", "MSc Chemistry", "PhD Chemistry"],
    biology: ["BSc Biology", "MSc Biology", "PhD Biology"],
    literature: ["BA Literature", "MA Literature", "PhD Literature"],
    };

    // Function to update course dropdown based on department selection
    function updateCourses() {
    const selectedDepartment = document.getElementById("department").value;
    const courseDropdown = document.getElementById("course");

    // Clear existing options
    courseDropdown.innerHTML = "";

    // Add default option
    const defaultOption = document.createElement("option");
    defaultOption.value = "";
    defaultOption.textContent = "Select Course";
    courseDropdown.appendChild(defaultOption);

    // Add courses for selected department
    if (selectedDepartment) {
        coursesByDepartment[selectedDepartment].forEach((course) => {
        const option = document.createElement("option");
        option.value = course;
        option.textContent = course;
        courseDropdown.appendChild(option);
        });
    }
    }

    // Attach event listener to department dropdown
    document.getElementById("department").addEventListener("change", updateCourses);

    // Update courses on page load
    updateCourses();
    // Get the modal
    var modal = document.getElementById("myModal");

    // Get the <span> element that closes the modal
    var span = document.getElementsByClassName("close")[0];

    // When the user clicks on <span> (x), close the modal
    span.onclick = function() {
        modal.style.display = "none";
    }

    // When the user clicks anywhere outside of the modal, close it
    window.onclick = function(event) {
        if (event.target == modal) {
            modal.style.display = "none";
        }
    }

    function showAlert() {
        if (confirm("Ready to submit?")) {
            modal.style.display = "block";
            document.getElementById("course-form").reset();
            return true;
  }
}
    
           
</script>
</html>

school_project/templates/header.html
{% load static %}
<header>
    <div class="container header justify-content-center mx-auto">
        <h1>Sky High</h1>
        <h3>International</h3>
    </div>
</header>

school_project/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en" data-bs-theme="light">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    <title>Sky High - Login</title>

    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    <script src="https://kit.fontawesome.com/0687cbebce.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

    <style>
        .form-rl {
            width: 30%;
            margin: auto;
            border: 1px solid black;
            border-radius: 9%;
            display: flex;
            justify-content: center;
            align-items: center;
            left: 50%;
            top: 50%;
            position: absolute;
            transform: translate(-50%,-50%);
        }
        table,tr,td {
            margin: auto;
            margin-top: 10px;
            padding: 10px;
        }
        form {
            margin: 20px;
        }
        input[type="submit"] {
            display: flex;
            left: 50%;
            padding: auto;
            margin-left: 70px;
            margin-right: 50px;
            width: auto;
            justify-content: center;
            align-items: center;
            transform: translateX(150%);
        }
        label {
            font-weight: bold;
        }
    </style>
</head>
<body>
    <div>
        {% include 'header.html' %}
    </div>
    <nav class="navbar navbar-expand-lg d-flex justify-content-center mx-auto">
        <div>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                      <li class="nav-item">
                          <a class="nav-link active" aria-current="page" href="/">Home</a>
                      </li>
                      {% if user.is_authenticated %}
                      <li class="nav-item">
                          <a class="nav-link active" aria-current="page" href="{% url 'credentials:logout' %}">Logout</a>
                      </li>
                      {% else %}
                      <li class="nav-item">
                          <a class="nav-link active" aria-current="page" href="{% url 'credentials:login' %}">Login</a>
                      </li>
                      <li class="nav-item">
                          <a class="nav-link active" aria-current="page" href="{% url 'credentials:register' %}">Register</a>
                      </li>
                      {% endif %}
                      <li class="nav-item dropdown">
                          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                              Department
                          </a>
                          <ul class="dropdown-menu">
                              {% for i in dept %}
                              <li><a class="dropdown-item" href="{{i.link}}">{{ i.dep_name }}</a></li>
                              {% endfor %}
                          </ul>
                      </li>
                  </ul>
            </div>
        </div>
    </nav>
    <div class="container form-rl">
        <form method="POST" action="login">
            {% csrf_token %}
            <table>
                <tr>
                    <td>
                        <label>Username </label>
                    </td>
                    <td>
                        <input type="text" name="username" placeholder="Enter your username"><br>
                    </td>
                </tr>
                <tr>
                    <td>
                        <label>Password </label>
                    </td>
                    <td>
                        <input type="password" name="password" placeholder="Enter your password"><br>
                    </td>
                </tr>
                <tr>
                    <td>
                       <input type="submit" value="login" class="btn btn-primary">
                    </td>
                </tr>
                <tr>
                    <td>
                        New here? <a type="button" class="btn btn-warning" href="{% url 'credentials:register' %}">register</a>
                    </td>
                </tr>
            </table>
        </form>
    </div>
    <br>
    <br><br><br>
    <div>
        <footer class="fixed-bottom bg-dark text-light py-3">
            <div class="container">
                <div class="row">
                    <div class="col-md-4">
                        <h5>About</h5>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                    </div>
                    <div class="col-md-4">
                        <h5>Contact</h5>
                        <p>Phone: +1 234 567 890</p>
                        <p>Email: example@example.com</p>
                    </div>
                    <div class="col-md-4">
                        <h5>Follow us on</h5>
                        <a href="https://www.facebook.com/" class="btn btn-light btn-sm mx-1">
                            <i class="fa-brands fa-facebook"></i>
                        </a>
                        <a href="https://www.instagram.com/" class="btn btn-light btn-sm mx-1">
                            <i class="fa-brands fa-instagram"></i>
                        </a>
                        <a href="https://twitter.com/i/flow/login" class="btn btn-light btn-sm mx-1">
                            <i class="fa-brands fa-twitter"></i>
                        </a>
                    </div>
                </div>
            </div>
        </footer>
     </div>
</body>
</html>

school_project/templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en" data-bs-theme="light">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    <title>Sky High - Register</title>

    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    <script src="https://kit.fontawesome.com/0687cbebce.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

    <style>
        .form-rl {
            width: 35%;
            margin: auto;
            /* padding: 10px; */
            border: 1px solid black;
            border-radius: 9%;
            display: flex;
            justify-content: center;
            align-items: center;
            left: 50%;
            top: 50%;
            position: absolute;
            transform: translate(-50%,-50%);
        }
        table,tr,td {
            margin: auto;
            margin-top: 10px;
            padding: 10px;
        }
        form {
            margin: 20px;
        }
        input[type="submit"] {
            display: flex;
            left: 50%;
            padding: auto;
            margin-left: 45px;
            margin-right: 60px;
            width: auto;
            justify-content: center;
            align-items: center;
            transform: translateX(150%);
        }
        label {
            font-weight: bold;
        }
    </style>

</head>
<body>
    <div>
        {% include 'header.html' %}
    </div>
    <nav class="navbar navbar-expand-lg d-flex justify-content-center mx-auto">
        <div>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                      <li class="nav-item">
                          <a class="nav-link active" aria-current="page" href="/">Home</a>
                      </li>
                      {% if user.is_authenticated %}
                      <li class="nav-item">
                          <a class="nav-link active" aria-current="page" href="{% url 'credentials:logout' %}">Logout</a>
                      </li>
                      {% else %}
                      <li class="nav-item">
                          <a class="nav-link active" aria-current="page" href="{% url 'credentials:login' %}">Login</a>
                      </li>
                      <li class="nav-item">
                          <a class="nav-link active" aria-current="page" href="{% url 'credentials:register' %}">Register</a>
                      </li>
                      {% endif %}
                      <li class="nav-item dropdown">
                          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                              Department
                          </a>
                          <ul class="dropdown-menu">
                              {% for i in dept %}
                              <li><a class="dropdown-item" href="{{i.link}}">{{ i.dep_name }}</a></li>
                              {% endfor %}
                          </ul>
                      </li>
                  </ul>
            </div>
        </div>
    </nav>
    <div class="container form-rl">
        <form method="POST" action="register">
            {% csrf_token %}
            <table>
                <tr>
                    <td>
                        <label>Username </label>
                    </td>
                    <td>
                        <input type="text" name="username" placeholder="Enter your username"><br>
                    </td>
                </tr>
                <tr>
                    <td>
                        <label>Password </label>
                    </td>
                    <td>
                        <input type="password" name="password" placeholder="Enter your password"><br>
                    </td>
                </tr>
                <tr>
                    <td>
                        <label>Confirm password </label>
                    </td>
                    <td>
                        <input type="password" name="c_password" placeholder="Enter the password again"><br>
                    </td>
                </tr>
                <tr>
                    <td>
                        <input type="submit" value="register" class="btn btn-primary">
                    </td>
                </tr>
                <tr>
                    <td>
                        Already have an account?
                        <a type="button" class="btn btn-dark" href="{% url 'credentials:login' %}">login</a>
                    </td>
                </tr>
            </table>
        </form>
    </div>
    <br>
    <br>
    <div>
       <footer class="fixed-bottom bg-dark text-light py-3">
           <div class="container">
               <div class="row">
                   <div class="col-md-4">
                       <h5>About</h5>
                       <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                   </div>
                   <div class="col-md-4">
                       <h5>Contact</h5>
                       <p>Phone: +1 234 567 890</p>
                       <p>Email: example@example.com</p>
                   </div>
                   <div class="col-md-4">
                       <h5>Follow us on</h5>
                       <a href="https://www.facebook.com/" class="btn btn-light btn-sm mx-1">
                           <i class="fa-brands fa-facebook"></i>
                       </a>
                       <a href="https://www.instagram.com/" class="btn btn-light btn-sm mx-1">
                           <i class="fa-brands fa-instagram"></i>
                       </a>
                       <a href="https://twitter.com/i/flow/login" class="btn btn-light btn-sm mx-1">
                           <i class="fa-brands fa-twitter"></i>
                       </a>
                   </div>
               </div>
           </div>
       </footer>
    </div>
</body>
</html>