movieproject/movieapp/urls.py
from . import views
from django.urls import path, include

app_name = 'movieapp'
urlpatterns = [

    path('', views.index, name='index'),
    path('movie/<int:movie_id>/', views.detail, name='detail'),
    path('add/', views.add_movie, name='add_movie'),
    path('update/<int:id>/', views.update_movie, name='update'),
    path('delete/<int:id>/', views.delete_movie, name='delete')

]

movieproject/movieproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("movieapp.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movieproject/movieapp/models.py
from django.db import models

# Create your models here.
class movie(models.Model):
    name = models.CharField(max_length=100)
    desc = models.TextField()
    year = models.IntegerField()
    img = models.ImageField(upload_to='gallery')
    dirc_name = models.TextField()


    def __str__(self):
        return self.name

movieproject/movieapp/forms.py
from django import forms
from . models import movie

class movieform(forms.ModelForm):
    class Meta:
        model = movie
        fields = ['name', 'desc', 'year', 'img', 'dirc_name']

movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from . models import movie
from . forms import movieform
# Create your views here.
def index(request):
    mov = movie.objects.all()
    context = {
        'movie_list': mov
    }
    return render(request, "index.html", context)

def detail(request, movie_id):
    mov = movie.objects.get(id=movie_id)
    return render(request, "detail.html", {'movie': mov})

def add_movie(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        desc = request.POST.get('desc')
        year = request.POST.get('year')
        img = request.FILES['img']
        dirc_name = request.POST.get('dirc_name')

        mov = movie(name=name, desc=desc, year=year, img=img, dirc_name=dirc_name)
        mov.save()
    return render(request, 'add_movie.html')
def update_movie(request, id):
    mov = movie.objects.get(id=id)
    form = movieform(request.POST or None, request.FILES, instance=mov)
    if form.is_valid():
        form.save()
        return redirect('/')

    return render(request, 'edit.html', {'form': form, 'movie': mov})

def delete_movie(request, id):
    if request.method == 'POST':
        mov = movie.objects.get(id=id)
        mov.delete()
        return redirect('/')
    return render(request, 'delete.html')

movieproject/templates/add_movie.html
{% extends 'base.html' %}
{% block body %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add movie</title>
</head>
<body>
    <br><br>
    <div class="container" id="form_container">
        <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
            <table>
                <caption>Movie details</caption>
                <tr>
                    <td>
                        <label>Movie name: </label>
                    </td>
                    <td>
                        <input type="text" name="name" placeholder="Enter the movie name">
                    </td>
                </tr>
                <tr>
                    <td>
                        <label>Description: </label>
                    </td>
                    <td>
                        <input type="text" name="desc" placeholder="Enter the movie description">
                    </td>
                </tr>
                <tr>
                    <td>
                        <label>Year: </label>
                    </td>
                    <td>
                        <input type="text" name="year" placeholder="Enter the release year">
                    </td>
                </tr>
                <tr>
                    <td>
                        <label>Director name: </label>
                    </td>
                    <td>
                        <input type="text" name="dirc_name" placeholder="Enter the name of the director">
                    </td>
                </tr>
                <tr>
                    <td>
                        <label>Image: </label>
                    </td>
                    <td>
                        <input type="file" name="img">
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        <input type="submit">
                    </td>
                </tr>
            </table>
        </form>
    </div>
</body>
</html>
{% endblock %}

movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<!--    <link rel="stylesheet" href="{% static 'style.css' %}">-->
    <title>index</title>
</head>
<body style="background-color: white;">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand mb-0 h1" href="{% url 'movieapp:index' %}">
<!--          <img src="/docs/5.3/assets/brand/bootstrap-logo.svg" alt="Logo" width="30" height="24" class="d-inline-block align-text-top">-->
          Movie House
        </a>
        <a class="navbar-brand" href="{% url 'movieapp:add_movie' %}">
            Add new
        </a>
      </div>
    </nav>
    {% block body %}
    {% endblock %}
</body>
</html>

movieproject/templates/delete.html
{% extends 'base.html' %}
{% block body %}
<form method="post">
    {% csrf_token %}
    <h3>Do you want to delete this data ?</h3>
    <br>
    <input type="submit" value="proceed">
</form>
{% endblock %}

movieproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.img.url}}" height="270">
        </div>
        <div class="col-md-6">
            <h2>{{movie.name}}</h2>
            <h5>{{movie.desc}}</h5>
            <h5>Year of release: {{movie.year}}</h5>
            <h5>Directed by: {{movie.dirc_name}}</h5>
            <a class="btn btn-primary" href="{% url 'movieapp:update' movie.id %}">update</a>
            &emsp;<a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">delete</a>
        </div>
    </div>
</div>

{% endblock %}

movieproject/templates/edit.html
{% extends 'base.html' %}
{% block body %}
    <title>update</title>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <br>
        <input type="submit" value="update">
    </form>
{% endblock %}

movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-md-3">
            <div class="card" style="width: 16rem;">
                <img class="card-img-top" src="{{i.img.url}}" alt="movie image" height="300">
                <div class="card-body">
                    <h5 class="card-title">{{i.name}}</h5>
<!--                    <p class="card-text"></p>-->
                    <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">know more</a>
                </div>
            </div>
            <br>
        </div>
        {% endfor %}
        <br><br>
    </div>
</div>

{% endblock %}